### PR TITLE
Add audio files

### PR DESCRIPTION
**Pull request by yongfei25**
Just grab these from github audio :)

### CODE REVIEW

**Comment by khayuenkam** [comment]
btw I am not familiar with ogg format. Do we need to support mp3 and ogg? Is it enough to just use mp3 file?

**Comment by yongfei25** [comment]
Not every browser support mp3 and vice versa. We can put multiple formats to ensure good browser coverage. Here I'm just following github.audio path.

btw the audio library https://github.com/goldfire/howler.js/

**Comment by yongfei25** [comment]
```
To avoid patent issues, support for MP3 is not built directly into Firefox. 
Instead it relies on support from the OS. Firefox supports this format on the following platforms: 
Windows Vista+ since Firefox 22.0, Android since Firefox 20.0, Firefox OS since Firefox 15.0, 
Linux since Firefox 26.0 (relies on GStreamer codecs) and OS X 10.7 since Firefox 35.0.
```

Quote from https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

**Review by khayuenkam — APPROVED** [review]
👍

**Pull request merged**
